name: Build

on: push

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          msbuild /target:drizzle /property:Configuration=Release drizzle.sln

      - name: Collect
        run: |
          mkdir upload
          move bin\Release\drizzle.exe upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: drizzle-windows
          path: upload

  build-sdl-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Dependencies
        run: |
          vcpkg integrate install
          vcpkg install sdl2:x64-windows

      - name: Build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          msbuild /target:drizzle /property:Configuration="Release SDL" drizzle.sln

      - name: Collect
        run: |
          mkdir upload
          move "bin\Release SDL\drizzle.exe" upload
          move "bin\Release SDL\SDL2.dll" upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: drizzle-sdl-windows
          path: upload

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Setup
        run: |
          mkdir drizzle/build

      - name: Build
        run: |
          cd drizzle/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-10 ..
          make -j 4

      - name: Collect
        run: |
          mkdir upload
          mv drizzle/build/drizzle upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: drizzle-linux
          path: upload

  build-sdl-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev

      - name: Setup
        run: |
          mkdir drizzle/build

      - name: Build
        run: |
          cd drizzle/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-10 -DENABLE_SDL2=ON ..
          make -j 4

      - name: Collect
        run: |
          mkdir upload
          mv drizzle/build/drizzle upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: drizzle-sdl-linux
          path: upload

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: <14

      - name: Setup
        run: |
          mkdir drizzle/build

      - name: Build
        run: |
          cd drizzle/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-11 ..
          make -j 4

      - name: Collect
        run: |
          mkdir upload
          mv drizzle/build/drizzle upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: drizzle-macos
          path: upload

  build-sdl-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: <14

      - name: Dependencies
        run: brew install sdl2

      - name: Setup
        run: |
          mkdir drizzle/build

      - name: Build
        run: |
          cd drizzle/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-11 -DENABLE_SDL2=ON ..
          make -j 4

      - name: Collect
        run: |
          mkdir upload
          mv drizzle/build/drizzle upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: drizzle-sdl-macos
          path: upload
